# 00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu118


In [48]:
cuda_available  = torch.cuda.is_available()
if cuda_available:
    device_name = torch.cuda.get_device_name(0)
    print(f"CUDA Device Name: {device_name}")

CUDA Device Name: Quadro K2200


# Introduction to Tensor
## Creating Tensors
torch.Tensor()

In [3]:
# Scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX
MATRIX = torch.tensor([[7, 9], [4, 3]])
MATRIX

tensor([[7, 9],
        [4, 3]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# Tensor
TENSOR = torch.tensor([[[4, 3, 2], [6, 32, 2]]])
TENSOR

tensor([[[ 4,  3,  2],
         [ 6, 32,  2]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 2, 3])

# Random Tensor

In [19]:
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.0132, 0.4295, 0.0439, 0.0313],
         [0.2823, 0.4761, 0.3417, 0.9601],
         [0.9098, 0.2871, 0.7525, 0.6815]]])

In [20]:
random_tensor.ndim

3

In [21]:
random_tensor.shape

torch.Size([1, 3, 4])

In [22]:
# Create a random tensor with similar shape of an image tensor
random_image_size_tensor =  torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and Ones

In [25]:
zeros = torch.zeros(size=(3, 3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [27]:
ones = torch.ones(size=(3, 3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

# Creating a range of tensors

In [34]:
# one_to_ten = torch.arange(1, 11)
one_to_ten = torch.arange(start=1, end=10, step=1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# Creating Tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor DataTypes
*Note:* Tensor datatypes is one of the 3 big errors in PyTorch & Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [50]:
# Float32 Tensor
float_32_tensor = torch.tensor([2.0, 5.0, 3.0],
                               dtype=None, # What datatype is your tensor(eg. float32 or float16)
                               device=None,# What device is your tensor on
                               requires_grad=False # Whether or not track the gradients with this tensor operations
                              )
float_32_tensor

tensor([2., 5., 3.])

In [51]:
float_32_tensor.dtype

torch.float32

In [52]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([2., 5., 3.], dtype=torch.float16)

In [53]:
int_32_tensor = float_32_tensor.type(torch.int32)
int_32_tensor

tensor([2, 5, 3], dtype=torch.int32)

In [54]:
int_32_tensor * float_32_tensor

tensor([ 4., 25.,  9.])

# Get Information from Tensors
1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype` 
2. Tensors not right shape - to get shape from tensor, can use `tensor.shape`
3. Tensors not on the right device - to get a device from a tensor, can use `tensor.device`

In [55]:
# Create Tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7086, 0.5851, 0.7621, 0.6143],
        [0.8349, 0.0536, 0.6494, 0.6956],
        [0.1861, 0.6014, 0.9281, 0.7583]])

In [57]:
# Find out details about some tensor
print(some_tensor, "\n")
print(f"DataType of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")


tensor([[0.7086, 0.5851, 0.7621, 0.6143],
        [0.8349, 0.0536, 0.6494, 0.6956],
        [0.1861, 0.6014, 0.9281, 0.7583]]) 

DataType of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


## Manipulating Tensors
### Tensor Operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [58]:
tensor = torch.tensor([1, 3, 5])

In [59]:
# Addition
tensor + 10

tensor([11, 13, 15])

In [60]:
# Subtraction 
tensor - 10 

tensor([-9, -7, -5])

In [61]:
# Multiplication
tensor * 10

tensor([10, 30, 50])

In [63]:
# Division
tensor / 5

tensor([0.2000, 0.6000, 1.0000])

In [68]:
# Matrix Multiplication
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(35)


In [69]:
tensor.matmul(tensor)

tensor(35)

# Matrix multiplication (is all you need)
One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:
 `(3, 2) @ (3, 2)` won't work
 `(2, 3) @ (3, 2)` will work
 `(3, 2) @ (2, 3)` will work
The resulting matrix has the shape of the outer dimensions:
 `(2, 3) @ (3, 2)` -> `(2, 2)`
 `(3, 2) @ (2, 3)` -> `(3, 3)`

 **Note:** "@" in Python is the symbol for matrix multiplication.

 **Resource:** You can see all of the rules for matrix multiplication using torch.matmul() in the PyTorch documentation.

In [3]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.5286, 0.5315],
        [0.5619, 0.6205]])

## One of the most common errors in DL: shape errors

In [5]:
# Shapes for matrix multiplication
tensor_A = torch.tensor(
        [[1, 2],
         [3, 4], 
         [5, 6], 
         [7, 8]]
)
tensor_B = torch.tensor(
        [[1, 2],
         [3, 4], 
         [5, 6], 
         [7, 8]]
)
tensor_A.shape, tensor_B.shape

(torch.Size([4, 2]), torch.Size([4, 2]))

### To fix our tensor shape issues, we can manipulate the shape of one of our tensor using **transpose**.

A **Transpose** switches the axis or dimentions for matrix

In [6]:
tensor_B, tensor_B.shape

(tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]),
 torch.Size([4, 2]))

In [7]:
tensor_B.T, tensor_B.T.shape

(tensor([[1, 3, 5, 7],
         [2, 4, 6, 8]]),
 torch.Size([2, 4]))

In [8]:
# Now, Multiply
torch.matmul(tensor_A, tensor_B.T)

tensor([[  5,  11,  17,  23],
        [ 11,  25,  39,  53],
        [ 17,  39,  61,  83],
        [ 23,  53,  83, 113]])

In [9]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([4, 2]), tensor_B = torch.Size([4, 2])

New shapes: tensor_A = torch.Size([4, 2]) (same as above), tensor_B.T = torch.Size([2, 4])

Multiplying: torch.Size([4, 2]) * torch.Size([2, 4]) <- inner dimensions match

Output:

tensor([[  5,  11,  17,  23],
        [ 11,  25,  39,  53],
        [ 17,  39,  61,  83],
        [ 23,  53,  83, 113]])

Output shape: torch.Size([4, 4])


## Find the min, max, mean, sum and etc (Tensor Aggregation)

In [10]:
# Create Tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [11]:
# minimum
torch.min(x), x.min()

(tensor(0), tensor(0))

In [12]:
# Maximum
torch.max(x), x.max()

(tensor(90), tensor(90))

In [15]:
# Mean 
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [16]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Find the positional min and max

In [17]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [21]:
torch.argmin(x), x.argmin() # return the minimum value index

(tensor(0), tensor(0))

In [22]:
torch.argmax(x), x.argmax() # return the maximum value index

(tensor(9), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing

In [23]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [24]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [26]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape
#Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.
#So changing the view changes the original tensor too.

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [27]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [29]:
# If we wanted to stack our new tensor on top of itself five times, we could do so with torch.stack().
torch.stack([x, x, x], dim=0)

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [32]:
x_stacted = torch.stack([x, x, x], dim=1)
x_stacted

tensor([[5., 5., 5.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.]])

#### Squeeze

In [46]:
reshaped_x = x_stacted.reshape(1, x_stacted.shape[0], x_stacted.shape[1])
reshaped_x, reshaped_x.shape

(tensor([[[5., 5., 5.],
          [2., 2., 2.],
          [3., 3., 3.],
          [4., 4., 4.],
          [5., 5., 5.],
          [6., 6., 6.],
          [7., 7., 7.]]]),
 torch.Size([1, 7, 3]))

In [49]:
x_squeezed = torch.squeeze(reshaped_x)
x_squeezed

tensor([[5., 5., 5.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.]])

In [50]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([[5., 5., 5.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.]])
Previous shape: torch.Size([7, 3])

New tensor: tensor([[[5., 5., 5.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.],
         [6., 6., 6.],
         [7., 7., 7.]]])
New shape: torch.Size([1, 7, 3])


In [51]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [57]:
x_permuted[0, 0, 0] = 32238

In [60]:
x_original

tensor([[[3.2238e+04, 4.2852e-01, 6.3957e-01],
         [3.2998e-01, 9.4714e-02, 9.0208e-01],
         [7.1187e-01, 2.8438e-01, 2.8899e-01],
         ...,
         [3.4741e-01, 2.0506e-01, 9.5081e-01],
         [8.9125e-01, 2.6352e-01, 4.2032e-01],
         [6.0079e-01, 5.4459e-01, 8.2016e-01]],

        [[8.6969e-01, 4.9074e-01, 4.4521e-01],
         [6.9862e-02, 7.0972e-01, 2.3369e-01],
         [4.2526e-01, 7.9322e-01, 8.6158e-01],
         ...,
         [7.2117e-01, 5.9521e-01, 1.0375e-01],
         [7.0762e-01, 8.1744e-01, 8.6922e-02],
         [9.1785e-01, 1.6030e-01, 2.7802e-01]],

        [[9.4222e-01, 6.7794e-01, 4.7585e-01],
         [4.3240e-01, 3.2291e-01, 8.5225e-01],
         [6.2540e-01, 7.1849e-01, 5.8896e-01],
         ...,
         [8.0063e-01, 9.3585e-01, 3.3609e-02],
         [7.4892e-01, 6.0609e-01, 2.5200e-01],
         [4.2307e-01, 6.6973e-01, 4.6882e-02]],

        ...,

        [[1.3727e-01, 3.3170e-02, 5.6324e-01],
         [1.5779e-01, 6.3599e-02, 3.8100e-02]

## Indexing (selecting data from tensors)

In [68]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [75]:
# Index on x to return 9
x[0, 2, 2]

tensor(9)

In [77]:
# Index on x to return [3, 6, 9]
x[:, :, 2]

tensor([[3, 6, 9]])

In [78]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [79]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [80]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [81]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

## PyTorch tensors & NumPy

In [82]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Note: By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).

However, many PyTorch calculations default to using float32.

So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use tensor = torch.from_numpy(array).type(torch.float32).

In [83]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [84]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [85]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))